name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - pip:
    - -r requirements.txt
