name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - pip:
    # local package
    - -e .
    # external requirements
    - python-dotenv>=0.5.1
    - tqdm
